# Generated by Django 4.2.27 on 2025-12-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('total_articles_collected', models.IntegerField()),
                ('top_keyword_1', models.CharField(blank=True, max_length=100)),
                ('top_keyword_2', models.CharField(blank=True, max_length=100)),
                ('top_keyword_3', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, help_text='기사 키워드 (쉼표 구분)'),
        ),
    ]
