# Generated by Django 4.2.27 on 2025-12-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_dailyreport_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('POLITICS', '정치'), ('ECONOMY', '경제'), ('SOCIETY', '사회'), ('INTERNATIONAL', '국제'), ('SPORTS', '스포츠'), ('CULTURE', '생활/문화'), ('ENTERTAINMENT', '연예')], max_length=20),
        ),
    ]
